{"version":3,"sources":["../../../units/rb-base-server/fsExists.js"],"names":["fs","fsWithCallbacks","promises","fsExists","path","access","err","code","NestedError"],"mappings":";;AAEA;;AAEA,gF;;AAEA,MAAMA,EAAE,GAAGC,YAAgBC,QAA3B;;AAEA;;AAE+BC,Q,GAAf,eAAeA,QAAf,CAAwBC,IAAxB,EAAsC;AACpD,MAAI;AACF,UAAMJ,EAAE,CAACK,MAAH,CAAUD,IAAV,CAAN;AACA,WAAO,IAAP;AACD,GAHD,CAGE,OAAOE,GAAP,EAAY;AACZ,QAAIA,GAAG,CAACC,IAAJ,KAAa,QAAjB,EAA2B,OAAO,KAAP,CAA3B;AACK;AACH,YAAM,IAAIC,0BAAJ,CAAgB,iCAAhB,EAAmDF,GAAnD,CAAN;AACD;AACF;AACF,C","sourcesContent":["// @flow\n\nimport fsWithCallbacks from 'fs'\n\nimport NestedError from 'nested-error-stacks'\n\nconst fs = fsWithCallbacks.promises\n\n//\n\nexport default (async function fsExists(path: string) {\n  try {\n    await fs.access(path)\n    return true\n  } catch (err) {\n    if (err.code === 'ENOENT') return false\n    else {\n      throw new NestedError('rb-base-server fsExists: Failed', err)\n    }\n  }\n})\n"],"file":"fsExists.js"}